

# level_map = [
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '                                                        ',
#     '  XXXX        XXXXXX                        XXXX        ',
#     '  XXXX        XXXXXX                        XXXX        ',
#     '  XXXX  P                                               ',
#     '  XXXX                                                  ',
#     '  XXXXXXXX                  XXXX                  XXXX  ',
#     '  XXXXXXXX                  XXXX                  XXXX  ',
#     '  XXXXXXXX              XXXX                            ',
#     '  XXXXXXXX              XXXX                            ',
#     '  XXXX        XX    XXXXXXXX        XXXX    XXXX        ',
#     '  XXXX        XX    XXXXXXXX        XXXX    XXXX        ',
#     '              XX    XXXXXXXX        XXXX    XXXXXX      ',
#     '              XX    XXXXXXXX        XXXX    XXXXXX      ',
#     '        XXXXXXXX    XXXXXXXXXXXX    XXXX    XXXXXXXX    ',
#     '        XXXXXXXX    XXXXXXXXXXXX    XXXX    XXXXXXXX    ',
#     'XXXXXXXXXXXXXXXX    XXXXXXXXXXXX    XXXX    XXXXXXXX    ',
#     'XXXXXXXXXXXXXXXX    XXXXXXXXXXXX    XXXX    XXXXXXXX    ']

level_map = [
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                        XXXX        XXXXXX                        XXXX        ',
    '                        XXXX        XXXXXX                        XXXX        ',
    '                        XXXX  P                                               ',
    '                        XXXX                                                  ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  XXXX                  XXXX  ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  XXXX                  XXXX  ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX              XXXX                            ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX              XXXX                            ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XX    XXXXXXXX        XXXX    XXXX        ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XX    XXXXXXXX        XXXX    XXXX        ',
    'XXXXXXXXXXXXXXXXXXXXXXXX            XX    XXXXXXXX        XXXX    XXXXXX      ',
    'XXXXXXXXXXXXXXXXXXXXXXXX            XX    XXXXXXXX        XXXX    XXXXXX      ',
    'XXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXXX    XXXXXXXXXXXX    XXXX    XXXXXXXX    ',
    'XXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXXX    XXXXXXXXXXXX    XXXX    XXXXXXXX    ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXX    XXXX    XXXXXXXX    ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXX    XXXX    XXXXXXXX    ']

tile_size = 16
screen_width = 1200
screen_height = len(level_map) * tile_size
